/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewSubmissionImport } from './routes/new-submission'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const NewSubmissionRoute = NewSubmissionImport.update({
  id: '/new-submission',
  path: '/new-submission',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/new-submission': {
      id: '/new-submission'
      path: '/new-submission'
      fullPath: '/new-submission'
      preLoaderRoute: typeof NewSubmissionImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-submission': typeof NewSubmissionRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-submission': typeof NewSubmissionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/new-submission': typeof NewSubmissionRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new-submission'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new-submission'
  id: '__root__' | '/' | '/new-submission'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewSubmissionRoute: typeof NewSubmissionRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewSubmissionRoute: NewSubmissionRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/new-submission"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/new-submission": {
      "filePath": "new-submission.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
